// <auto-generated />
using System;
using LLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLibrary.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260524082419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LLibrary.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            BirthDate = new DateTime(1828, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Лев",
                            LastName = "Толстой"
                        },
                        new
                        {
                            AuthorId = 2,
                            BirthDate = new DateTime(1821, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Фёдор",
                            LastName = "Достоевский"
                        });
                });

            modelBuilder.Entity("LLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasFilter("[ISBN] IS NOT NULL");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            ISBN = "978-5-17-01",
                            Title = "Война и мир"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 1,
                            ISBN = "978-5-17-02",
                            Title = "Анна Каренина"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            ISBN = "978-5-17-03",
                            Title = "Преступление и наказание"
                        });
                });

            modelBuilder.Entity("LLibrary.Models.BookMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int?>("ToLocationId")
                        .HasColumnType("int");

                    b.HasKey("MovementId");

                    b.HasIndex("BookId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ReaderId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("BookMovements");
                });

            modelBuilder.Entity("LLibrary.Models.Reader", b =>
                {
                    b.Property<int>("ReaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReaderId"));

                    b.Property<string>("ClassNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReaderId");

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            ReaderId = 1,
                            ClassNumber = "10-А",
                            FirstName = "Иван",
                            LastName = "Иванов"
                        },
                        new
                        {
                            ReaderId = 2,
                            ClassNumber = "9-Б",
                            FirstName = "Петр",
                            LastName = "Петров"
                        });
                });

            modelBuilder.Entity("LLibrary.Models.StorageLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.ToTable("StorageLocations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Room = "Читальный зал",
                            Shelf = "Стеллаж 1"
                        },
                        new
                        {
                            LocationId = 2,
                            Room = "Архив",
                            Shelf = "Стеллаж 10"
                        });
                });

            modelBuilder.Entity("LLibrary.Models.Book", b =>
                {
                    b.HasOne("LLibrary.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LLibrary.Models.BookMovement", b =>
                {
                    b.HasOne("LLibrary.Models.Book", "Book")
                        .WithMany("Movements")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LLibrary.Models.StorageLocation", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId");

                    b.HasOne("LLibrary.Models.Reader", "Reader")
                        .WithMany("Movements")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LLibrary.Models.StorageLocation", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId");

                    b.Navigation("Book");

                    b.Navigation("FromLocation");

                    b.Navigation("Reader");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("LLibrary.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LLibrary.Models.Book", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("LLibrary.Models.Reader", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
